version: "3"

services:
    db:
        image: postgres:14
        platform: linux/x86_64
        container_name: forum_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: forum_db
            POSTGRES_USER: forum_user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres_data:/var/lib/postgresql/data
        networks:
            - forum_app

networks:
    forum_app:
        driver: bridge
